### ISSUE TITLE
Missing Chart?

### ISSUE THREAD

**Issue by nspp99b** [learn-co-students/instant-datascience-data-science-pilot#1]
"Here is a chart that Colin Morris produced showing some of the most repetitive popular artists. How was something like this made and calculated?"

Is a chart or graph supposed to follow this sentence?  If so I'm not seeing it, even on refresh.

**Comment by ddbrennan** [comment]
Also not loading for me.

**Comment by walkingalchemy** [comment]
+1

**Comment by iamm28** [comment]
Same

**Comment by yoyothesheep** [comment]
Assigned to Jeff because I think it's because we're lacking some config file in the lesson (not sure). Please take a look.

**Comment by tkoar** [comment]
chart has been added to s3 and should display properly now
