### ISSUE TITLE
gray boxes

### ISSUE THREAD

**Issue by Josh-Stillman** [learn-co-students/instant-datascience-data-science-pilot#2]
There are two gray boxes, which is a bit confusing.  I'd say instead "The content in the **first** gray box is the code you type in. "  The second box is the output.

**Comment by ddbrennan** [comment]
+1 

Also weird that this paragraph is in its own gray box

**Comment by tkoar** [comment]
This confusion is due to the style conversion from jupyter notebook to github markdown. The wording has been updated to be clearer.

**Comment by yoyothesheep** [comment]
What about - displaying screenshots of the Jupyter cells? The styling is still confusing and the updated wording just helps a little.
