### ISSUE TITLE
Excess text

### ISSUE THREAD

**Issue by misslesliehsu** [learn-co-students/instant-datascience-data-science-pilot#6]
Just before the SUMMARY section - there is hanging code in plain text:

import plotly from plotly.offline import iplot, init_notebook_mode from plotly import tools import plotly.graph_objs as go init_notebook_mode(connected=True)

trace = {'type': 'bar', 'x': list(unique_words), 'y': list(word_histogram.values())} plotly.offline.iplot({'data': [trace]})

**Comment by tkoar** [comment]
This has been fixed on a branch and will be merged in.
