### ISSUE TITLE
looks like this should be something it is not

### ISSUE THREAD

**Issue by L-A-Davis** [learn-co-students/instant-datascience-data-science-pilot#9]
import plotly from plotly.offline import iplot, init_notebook_mode from plotly import tools import plotly.graph_objs as go init_notebook_mode(connected=True)

trace = {'type': 'bar', 'x': list(unique_words), 'y': list(word_histogram.values())} plotly.offline.iplot({'data': [trace]})

**Comment by tkoar** [comment]
Please refer to #6
